### PR TITLE
add new provider and tlds endpoints

### PR DESCRIPTION
**Pull request by johannafransn**
- Added new TLDS and provider(s) endpoints
- Small changes to intro to reflect new wording

### CODE REVIEW

**Review by iamvkv — CHANGES_REQUESTED** [review]
Thanks Johanna! LGTM, just need to update the link for getting a permanent API key in the text from Weightless to Google Forms

"To request a permanent API_KEY, apply [here](https://forms.gle/XikEsdYrqvXrbRhR6) and we will get back to you within 72 hours"

@thomas779 do we also need to update the following with the latest rate limit/validity?

Note: as a free service the rate limit is 15 requests per minute per API_KEY.
Note: the Trial API_KEY is valid for 15 minutes.

**Comment by thomas779** [comment]
> Thanks Johanna! Looks great. Two comments:
> 
> 1. Need to update the link for getting a permanent API key in the text from Weightless to Google Forms
>    "To request a permanent API_KEY apply [here](https://forms.gle/XikEsdYrqvXrbRhR6) and we will get back to you within 72 hours"
> 2. @thomas779 do we also need to update the following with the latest rate limit/validity?
>    Note: as a free service the rate limit is 15 requests per minute per API_KEY.
>    Note: the Trial API_KEY is valid for 15 minutes.
Yes, good point. It should be:
Note: A trial API_KEY can be generated 15 times per day.

Each API_KEY is valid for 15 minutes from the moment of creation. That still should be the same. 
```js
endpoints.requestToken = {
  url: "/try",
  method: "get",
  middleware: [middleware.validateRequestTempToken],
  handler: tempTokenHandler.requestToken,
  rateLimit: {
    max: 15,
    timeWindow: "1 day",
    // ban: 2,
  },
  description: "Request a temporary api key",
};```

@iamvkv did we want to change the number of API keys created?

**Comment by iamvkv** [comment]
I sometimes hit the limit during regular testing throughout the day. It would be good to bump it to 30 keys/day, IMO

That would allow for testing but still limit someone's ability to use trial keys in production

**Review by thomas779 — APPROVED** [review]
Let's merge this one and start another PR!

**Review by iamvkv — APPROVED** [review]
LGTM

**Pull request merged**
